import type { BlogPost, Pin } from "@/types";
import { CATEGORIES } from "./categories";

// Products imported from Pinterest: https://www.pinterest.com/veerababupalepu549/
export const MOCK_PINS: Pin[] = [
  {
    id: "1",
    title: "5 Simple Men's Fashion Tips to Elevate Your Style",
    slug: "5-simple-mens-fashion-tips-to-elevate-your-style",
    seoTitle: "5 Simple Men's Fashion Tips to Elevate Your Style | Fashion Loot Deals",
    shortDescription: "Discover smart casual outfit ideas, style essentials, and confidence-boosting looks for everyday wear, office outfits, a...",
    fullDescription: "Discover smart casual outfit ideas, style essentials, and confidence-boosting looks for everyday wear, office outfits, and date nights. Shop now on Amazon before this deal ends!",
    pinterestTitle: "5 Simple Men's Fashion Tips to Elevate Your Style ✨",
    pinterestDescription: "Discover smart casual outfit ideas, style essentials, and confidence-boosting looks for everyday wear, office outfits, and date nights. #AmazonFinds #FashionLootDeals",
    metaDescription: "Discover smart casual outfit ideas, style essentials, and confidence-boosting looks for everyday wear, office outfits, and date nights.",
    seoKeywords: "5 simple men's fashion tips to elevate your style, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4g6fj7T",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: false,
    views: 4032,
    likes: 795,
    saves: 1413,
    amazonClicks: 82,
    pinterestClicks: 349,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "1a", url: "https://i.pinimg.com/736x/48/ea/71/48ea71427f6ba8913b80102e0b4ee9e2.jpg", alt: "5 Simple Men's Fashion Tips to Elevate Your Style", sortOrder: 0 }],
    tags: [{ id: "t1", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "2",
    title: "Men's Olive Green Casual Shirt Outfit",
    slug: "mens-olive-green-casual-shirt-outfit",
    seoTitle: "Men's Olive Green Casual Shirt Outfit | Fashion Loot Deals",
    shortDescription: "Stylish olive green casual shirt perfect for everyday wear, office outfits, date nights, and weekend style.",
    fullDescription: "Stylish olive green casual shirt perfect for everyday wear, office outfits, date nights, and weekend style. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Olive Green Casual Shirt Outfit ✨",
    pinterestDescription: "Stylish olive green casual shirt perfect for everyday wear, office outfits, date nights, and weekend style. #AmazonFinds #FashionLootDeals",
    metaDescription: "Stylish olive green casual shirt perfect for everyday wear, office outfits, date nights, and weekend style.",
    seoKeywords: "men's olive green casual shirt outfit, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/43iA34U",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: false,
    views: 9378,
    likes: 360,
    saves: 847,
    amazonClicks: 326,
    pinterestClicks: 260,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "2a", url: "https://i.pinimg.com/736x/8b/4c/df/8b4cdf7103d0a90050c48464bd0b133f.jpg", alt: "Men's Olive Green Casual Shirt Outfit", sortOrder: 0 }],
    tags: [{ id: "t2", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "3",
    title: "Classic Striped Shirt for Men | Slim Fit Smart Casual",
    slug: "classic-striped-shirt-for-men-slim-fit-smart-casual",
    seoTitle: "Classic Striped Shirt for Men | Slim Fit Smart Casual | Fashion Loot Deals",
    shortDescription: "Classic striped shirt for men — perfect for office casual, date nights, and weekend outfits with grey jeans.",
    fullDescription: "Classic striped shirt for men — perfect for office casual, date nights, and weekend outfits with grey jeans. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Classic Striped Shirt for Men | Slim Fit Smart Casual ✨",
    pinterestDescription: "Classic striped shirt for men — perfect for office casual, date nights, and weekend outfits with grey jeans. #AmazonFinds #FashionLootDeals",
    metaDescription: "Classic striped shirt for men — perfect for office casual, date nights, and weekend outfits with grey jeans.",
    seoKeywords: "classic striped shirt for men | slim fit smart casual, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4dQUHiB",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 8607,
    likes: 317,
    saves: 1672,
    amazonClicks: 284,
    pinterestClicks: 788,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "3a", url: "https://i.pinimg.com/736x/32/19/a9/3219a999259bdb1812a85b8b1b6e0752.jpg", alt: "Classic Striped Shirt for Men | Slim Fit Smart Casual", sortOrder: 0 }],
    tags: [{ id: "t3", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "4",
    title: "Men's Summer Casual Color Block Shirt",
    slug: "mens-summer-casual-color-block-shirt",
    seoTitle: "Men's Summer Casual Color Block Shirt | Fashion Loot Deals",
    shortDescription: "Lightweight short-sleeve color block shirt for summer, beach vacations, and casual streetwear.",
    fullDescription: "Lightweight short-sleeve color block shirt for summer, beach vacations, and casual streetwear. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Summer Casual Color Block Shirt ✨",
    pinterestDescription: "Lightweight short-sleeve color block shirt for summer, beach vacations, and casual streetwear. #AmazonFinds #FashionLootDeals",
    metaDescription: "Lightweight short-sleeve color block shirt for summer, beach vacations, and casual streetwear.",
    seoKeywords: "men's summer casual color block shirt, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4alLGM7",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 16013,
    likes: 415,
    saves: 372,
    amazonClicks: 385,
    pinterestClicks: 993,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "4a", url: "https://i.pinimg.com/736x/fb/91/1b/fb911bdd8afb66ecf6c6a248982d0e74.jpg", alt: "Men's Summer Casual Color Block Shirt", sortOrder: 0 }],
    tags: [{ id: "t4", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "5",
    title: "Men's Casual Co-Ord Set | Textured Overshirt",
    slug: "mens-casual-co-ord-set-textured-overshirt",
    seoTitle: "Men's Casual Co-Ord Set | Textured Overshirt | Fashion Loot Deals",
    shortDescription: "Premium textured overshirt with matching relaxed-fit bottoms. Perfect for travel, weekend wear, and smart-casual occasio...",
    fullDescription: "Premium textured overshirt with matching relaxed-fit bottoms. Perfect for travel, weekend wear, and smart-casual occasions. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Casual Co-Ord Set | Textured Overshirt ✨",
    pinterestDescription: "Premium textured overshirt with matching relaxed-fit bottoms. Perfect for travel, weekend wear, and smart-casual occasions. #AmazonFinds #FashionLootDeals",
    metaDescription: "Premium textured overshirt with matching relaxed-fit bottoms. Perfect for travel, weekend wear, and smart-casual occasions.",
    seoKeywords: "men's casual co-ord set | textured overshirt, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4u98PIM",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: false,
    views: 3878,
    likes: 384,
    saves: 1374,
    amazonClicks: 513,
    pinterestClicks: 641,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "5a", url: "https://i.pinimg.com/736x/32/19/47/321947e4e5dc421c53488c1c9bf286e5.jpg", alt: "Men's Casual Co-Ord Set | Textured Overshirt", sortOrder: 0 }],
    tags: [{ id: "t5", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "6",
    title: "Men's Black Shirt Jacket | Everyday Essential",
    slug: "mens-black-shirt-jacket-everyday-essential",
    seoTitle: "Men's Black Shirt Jacket | Everyday Essential | Fashion Loot Deals",
    shortDescription: "Versatile black shirt jacket that pairs effortlessly with jeans, chinos, and sneakers.",
    fullDescription: "Versatile black shirt jacket that pairs effortlessly with jeans, chinos, and sneakers. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Black Shirt Jacket | Everyday Essential ✨",
    pinterestDescription: "Versatile black shirt jacket that pairs effortlessly with jeans, chinos, and sneakers. #AmazonFinds #FashionLootDeals",
    metaDescription: "Versatile black shirt jacket that pairs effortlessly with jeans, chinos, and sneakers.",
    seoKeywords: "men's black shirt jacket | everyday essential, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/49Bn7L7",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 9919,
    likes: 897,
    saves: 1583,
    amazonClicks: 148,
    pinterestClicks: 755,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "6a", url: "https://i.pinimg.com/736x/23/9d/ff/239dffbe716114ec763c9821b018aad8.jpg", alt: "Men's Black Shirt Jacket | Everyday Essential", sortOrder: 0 }],
    tags: [{ id: "t6", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "7",
    title: "Tropical Hawaiian Shirt for Men | Summer Vacation",
    slug: "tropical-hawaiian-shirt-for-men-summer-vacation",
    seoTitle: "Tropical Hawaiian Shirt for Men | Summer Vacation | Fashion Loot Deals",
    shortDescription: "Lightweight tropical Hawaiian shirt for beach vacations, cruises, and weekend adventures.",
    fullDescription: "Lightweight tropical Hawaiian shirt for beach vacations, cruises, and weekend adventures. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Tropical Hawaiian Shirt for Men | Summer Vacation ✨",
    pinterestDescription: "Lightweight tropical Hawaiian shirt for beach vacations, cruises, and weekend adventures. #AmazonFinds #FashionLootDeals",
    metaDescription: "Lightweight tropical Hawaiian shirt for beach vacations, cruises, and weekend adventures.",
    seoKeywords: "tropical hawaiian shirt for men | summer vacation, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4vgmRcC",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 3082,
    likes: 287,
    saves: 920,
    amazonClicks: 342,
    pinterestClicks: 479,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "7a", url: "https://i.pinimg.com/736x/0c/a7/40/0ca7403e54b203ab8c07cff47a2a805d.jpg", alt: "Tropical Hawaiian Shirt for Men | Summer Vacation", sortOrder: 0 }],
    tags: [{ id: "t7", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "8",
    title: "Men's Fashion Hack | Look Expensive on a Budget",
    slug: "mens-fashion-hack-look-expensive-on-a-budget",
    seoTitle: "Men's Fashion Hack | Look Expensive on a Budget | Fashion Loot Deals",
    shortDescription: "Trendy striped shirt look for casual outings, date nights, and smart-casual events.",
    fullDescription: "Trendy striped shirt look for casual outings, date nights, and smart-casual events. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Fashion Hack | Look Expensive on a Budget ✨",
    pinterestDescription: "Trendy striped shirt look for casual outings, date nights, and smart-casual events. #AmazonFinds #FashionLootDeals",
    metaDescription: "Trendy striped shirt look for casual outings, date nights, and smart-casual events.",
    seoKeywords: "men's fashion hack | look expensive on a budget, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4x3k5sZ",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 11891,
    likes: 771,
    saves: 384,
    amazonClicks: 473,
    pinterestClicks: 861,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "8a", url: "https://i.pinimg.com/736x/9d/a2/e2/9da2e2390a96a8b35c0d7e970943ddf0.jpg", alt: "Men's Fashion Hack | Look Expensive on a Budget", sortOrder: 0 }],
    tags: [{ id: "t8", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "9",
    title: "Premium Men's Shirt Under ₹399",
    slug: "premium-mens-shirt-under-399",
    seoTitle: "Premium Men's Shirt Under ₹399 | Fashion Loot Deals",
    shortDescription: "Soft, breathable premium men's shirt for casual outings, office wear, and vacations. Limited stock!",
    fullDescription: "Soft, breathable premium men's shirt for casual outings, office wear, and vacations. Limited stock! Shop now on Amazon before this deal ends!",
    pinterestTitle: "Premium Men's Shirt Under ₹399 ✨",
    pinterestDescription: "Soft, breathable premium men's shirt for casual outings, office wear, and vacations. Limited stock! #AmazonFinds #FashionLootDeals",
    metaDescription: "Soft, breathable premium men's shirt for casual outings, office wear, and vacations. Limited stock!",
    seoKeywords: "premium men's shirt under ₹399, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/3RzabPH",
    price: 399,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 9614,
    likes: 720,
    saves: 989,
    amazonClicks: 268,
    pinterestClicks: 626,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "9a", url: "https://i.pinimg.com/736x/96/f0/38/96f0383e005579f5fb88be043382752b.jpg", alt: "Premium Men's Shirt Under ₹399", sortOrder: 0 }],
    tags: [{ id: "t9", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "10",
    title: "Premium Black Resort Collar Shirt | Minimalist Style",
    slug: "premium-black-resort-collar-shirt-minimalist-style",
    seoTitle: "Premium Black Resort Collar Shirt | Minimalist Style | Fashion Loot Deals",
    shortDescription: "Clean minimalist black resort collar shirt for summer vacations, date nights, and smart-casual styling.",
    fullDescription: "Clean minimalist black resort collar shirt for summer vacations, date nights, and smart-casual styling. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Premium Black Resort Collar Shirt | Minimalist Style ✨",
    pinterestDescription: "Clean minimalist black resort collar shirt for summer vacations, date nights, and smart-casual styling. #AmazonFinds #FashionLootDeals",
    metaDescription: "Clean minimalist black resort collar shirt for summer vacations, date nights, and smart-casual styling.",
    seoKeywords: "premium black resort collar shirt | minimalist style, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/3S8XXgG",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 12510,
    likes: 867,
    saves: 1666,
    amazonClicks: 402,
    pinterestClicks: 591,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "10a", url: "https://i.pinimg.com/736x/69/e0/45/69e045fff6d3008c3af9af7314bc5565.jpg", alt: "Premium Black Resort Collar Shirt | Minimalist Style", sortOrder: 0 }],
    tags: [{ id: "t10", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "11",
    title: "Tropical Print Shirt | Summer Fashion Under ₹413",
    slug: "tropical-print-shirt-summer-fashion-under-413",
    seoTitle: "Tropical Print Shirt | Summer Fashion Under ₹413 | Fashion Loot Deals",
    shortDescription: "Stylish tropical print shirt with premium breathable fabric. Perfect for beach vacations and parties.",
    fullDescription: "Stylish tropical print shirt with premium breathable fabric. Perfect for beach vacations and parties. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Tropical Print Shirt | Summer Fashion Under ₹413 ✨",
    pinterestDescription: "Stylish tropical print shirt with premium breathable fabric. Perfect for beach vacations and parties. #AmazonFinds #FashionLootDeals",
    metaDescription: "Stylish tropical print shirt with premium breathable fabric. Perfect for beach vacations and parties.",
    seoKeywords: "tropical print shirt | summer fashion under ₹413, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/49vdLAt",
    price: 413,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 7803,
    likes: 664,
    saves: 1540,
    amazonClicks: 337,
    pinterestClicks: 988,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "11a", url: "https://i.pinimg.com/736x/6c/dd/1b/6cdd1bbda6af81244014dbf88292cd22.jpg", alt: "Tropical Print Shirt | Summer Fashion Under ₹413", sortOrder: 0 }],
    tags: [{ id: "t11", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "12",
    title: "Premium Navy Blue Polo T-Shirt Under ₹449",
    slug: "premium-navy-blue-polo-t-shirt-under-449",
    seoTitle: "Premium Navy Blue Polo T-Shirt Under ₹449 | Fashion Loot Deals",
    shortDescription: "Premium breathable polo with modern athletic fit. Perfect for casual, college, and travel looks.",
    fullDescription: "Premium breathable polo with modern athletic fit. Perfect for casual, college, and travel looks. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Premium Navy Blue Polo T-Shirt Under ₹449 ✨",
    pinterestDescription: "Premium breathable polo with modern athletic fit. Perfect for casual, college, and travel looks. #AmazonFinds #FashionLootDeals",
    metaDescription: "Premium breathable polo with modern athletic fit. Perfect for casual, college, and travel looks.",
    seoKeywords: "premium navy blue polo t-shirt under ₹449, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4vjeRb3",
    price: 449,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 16261,
    likes: 170,
    saves: 435,
    amazonClicks: 443,
    pinterestClicks: 391,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "12a", url: "https://i.pinimg.com/736x/24/44/91/24449118cf4d6b87db5235b0f20f365c.jpg", alt: "Premium Navy Blue Polo T-Shirt Under ₹449", sortOrder: 0 }],
    tags: [{ id: "t12", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "13",
    title: "Gradient Casual Shirt for Men Under ₹310",
    slug: "gradient-casual-shirt-for-men-under-310",
    seoTitle: "Gradient Casual Shirt for Men Under ₹310 | Fashion Loot Deals",
    shortDescription: "Stylish ombre gradient shirt with soft breathable fabric for beach outings and everyday wear.",
    fullDescription: "Stylish ombre gradient shirt with soft breathable fabric for beach outings and everyday wear. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Gradient Casual Shirt for Men Under ₹310 ✨",
    pinterestDescription: "Stylish ombre gradient shirt with soft breathable fabric for beach outings and everyday wear. #AmazonFinds #FashionLootDeals",
    metaDescription: "Stylish ombre gradient shirt with soft breathable fabric for beach outings and everyday wear.",
    seoKeywords: "gradient casual shirt for men under ₹310, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4nN2QrC",
    price: 310,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 13561,
    likes: 647,
    saves: 476,
    amazonClicks: 328,
    pinterestClicks: 783,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "13a", url: "https://i.pinimg.com/736x/b3/6f/7b/b36f7b877c24412f164b9659b21861f6.jpg", alt: "Gradient Casual Shirt for Men Under ₹310", sortOrder: 0 }],
    tags: [{ id: "t13", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "14",
    title: "Men's Party Wear Shirt Under ₹449",
    slug: "mens-party-wear-shirt-under-449",
    seoTitle: "Men's Party Wear Shirt Under ₹449 | Fashion Loot Deals",
    shortDescription: "Premium party wear shirt with luxury embroidery design. Perfect for weddings and date nights.",
    fullDescription: "Premium party wear shirt with luxury embroidery design. Perfect for weddings and date nights. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Men's Party Wear Shirt Under ₹449 ✨",
    pinterestDescription: "Premium party wear shirt with luxury embroidery design. Perfect for weddings and date nights. #AmazonFinds #FashionLootDeals",
    metaDescription: "Premium party wear shirt with luxury embroidery design. Perfect for weddings and date nights.",
    seoKeywords: "men's party wear shirt under ₹449, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4dTzfIK",
    price: 449,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 2411,
    likes: 442,
    saves: 850,
    amazonClicks: 477,
    pinterestClicks: 548,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "14a", url: "https://i.pinimg.com/736x/84/5f/12/845f121e6563b593726ddef606fc89cf.jpg", alt: "Men's Party Wear Shirt Under ₹449", sortOrder: 0 }],
    tags: [{ id: "t14", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "15",
    title: "Printed Casual Shirt Under ₹378",
    slug: "printed-casual-shirt-under-378",
    seoTitle: "Printed Casual Shirt Under ₹378 | Fashion Loot Deals",
    shortDescription: "Trending geometric print shirt for vacations, beach outings, and summer fashion.",
    fullDescription: "Trending geometric print shirt for vacations, beach outings, and summer fashion. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Printed Casual Shirt Under ₹378 ✨",
    pinterestDescription: "Trending geometric print shirt for vacations, beach outings, and summer fashion. #AmazonFinds #FashionLootDeals",
    metaDescription: "Trending geometric print shirt for vacations, beach outings, and summer fashion.",
    seoKeywords: "printed casual shirt under ₹378, amazon finds, fashion loot deals, mens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #mensfashion",
    affiliateLink: "https://amzn.to/4v6P45w",
    price: 378,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 3731,
    likes: 322,
    saves: 1661,
    amazonClicks: 121,
    pinterestClicks: 403,
    category: CATEGORIES.find((c) => c.slug === "mens-fashion")!,
    images: [{ id: "15a", url: "https://i.pinimg.com/736x/7c/6e/3b/7c6e3bbdcccf9f9d2daaf94c5f73fea3.jpg", alt: "Printed Casual Shirt Under ₹378", sortOrder: 0 }],
    tags: [{ id: "t15", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "16",
    title: "Traditional Lehenga for Women | Wedding & Party Wear",
    slug: "traditional-lehenga-for-women-wedding-party-wear",
    seoTitle: "Traditional Lehenga for Women | Wedding & Party Wear | Fashion Loot Deals",
    shortDescription: "Beautiful traditional lehenga with premium fabric and elegant detailing for weddings and festivals.",
    fullDescription: "Beautiful traditional lehenga with premium fabric and elegant detailing for weddings and festivals. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Traditional Lehenga for Women | Wedding & Party Wear ✨",
    pinterestDescription: "Beautiful traditional lehenga with premium fabric and elegant detailing for weddings and festivals. #AmazonFinds #FashionLootDeals",
    metaDescription: "Beautiful traditional lehenga with premium fabric and elegant detailing for weddings and festivals.",
    seoKeywords: "traditional lehenga for women | wedding & party wear, amazon finds, fashion loot deals, womens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #womensfashion",
    affiliateLink: "https://amzn.to/4tzWqxf",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: false,
    views: 6990,
    likes: 831,
    saves: 909,
    amazonClicks: 458,
    pinterestClicks: 584,
    category: CATEGORIES.find((c) => c.slug === "womens-fashion")!,
    images: [{ id: "16a", url: "https://i.pinimg.com/736x/51/ea/0e/51ea0ee2cb6d2c32ce93bdde7fc8bced.jpg", alt: "Traditional Lehenga for Women | Wedding & Party Wear", sortOrder: 0 }],
    tags: [{ id: "t16", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "17",
    title: "Elegant Lehenga Dress for Women | Ethnic Party Wear",
    slug: "elegant-lehenga-dress-for-women-ethnic-party-wear",
    seoTitle: "Elegant Lehenga Dress for Women | Ethnic Party Wear | Fashion Loot Deals",
    shortDescription: "Rich traditional embroidery lehenga perfect for weddings, festivals, and receptions.",
    fullDescription: "Rich traditional embroidery lehenga perfect for weddings, festivals, and receptions. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Elegant Lehenga Dress for Women | Ethnic Party Wear ✨",
    pinterestDescription: "Rich traditional embroidery lehenga perfect for weddings, festivals, and receptions. #AmazonFinds #FashionLootDeals",
    metaDescription: "Rich traditional embroidery lehenga perfect for weddings, festivals, and receptions.",
    seoKeywords: "elegant lehenga dress for women | ethnic party wear, amazon finds, fashion loot deals, womens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #womensfashion",
    affiliateLink: "https://amzn.to/43dHwSx",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 7835,
    likes: 897,
    saves: 2165,
    amazonClicks: 543,
    pinterestClicks: 137,
    category: CATEGORIES.find((c) => c.slug === "womens-fashion")!,
    images: [{ id: "17a", url: "https://i.pinimg.com/736x/b5/7c/39/b57c39340851d2df08d2ca5f9e9000d8.jpg", alt: "Elegant Lehenga Dress for Women | Ethnic Party Wear", sortOrder: 0 }],
    tags: [{ id: "t17", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "18",
    title: "Affordable Purple Georgette Saree Under ₹350",
    slug: "affordable-purple-georgette-saree-under-350",
    seoTitle: "Affordable Purple Georgette Saree Under ₹350 | Fashion Loot Deals",
    shortDescription: "Premium georgette saree with lightweight comfort for parties, festivals, and daily elegance.",
    fullDescription: "Premium georgette saree with lightweight comfort for parties, festivals, and daily elegance. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Affordable Purple Georgette Saree Under ₹350 ✨",
    pinterestDescription: "Premium georgette saree with lightweight comfort for parties, festivals, and daily elegance. #AmazonFinds #FashionLootDeals",
    metaDescription: "Premium georgette saree with lightweight comfort for parties, festivals, and daily elegance.",
    seoKeywords: "affordable purple georgette saree under ₹350, amazon finds, fashion loot deals, womens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #womensfashion",
    affiliateLink: "https://amzn.to/4uzxhnq",
    price: 350,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 5683,
    likes: 263,
    saves: 1063,
    amazonClicks: 395,
    pinterestClicks: 352,
    category: CATEGORIES.find((c) => c.slug === "womens-fashion")!,
    images: [{ id: "18a", url: "https://i.pinimg.com/736x/ca/0e/5c/ca0e5cd1298b64b75f2429c407c54bb7.jpg", alt: "Affordable Purple Georgette Saree Under ₹350", sortOrder: 0 }],
    tags: [{ id: "t18", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "19",
    title: "Purple Anarkali Dress Under ₹899",
    slug: "purple-anarkali-dress-under-899",
    seoTitle: "Purple Anarkali Dress Under ₹899 | Fashion Loot Deals",
    shortDescription: "Gorgeous Anarkali dress with embroidered detailing for festive occasions and parties.",
    fullDescription: "Gorgeous Anarkali dress with embroidered detailing for festive occasions and parties. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Purple Anarkali Dress Under ₹899 ✨",
    pinterestDescription: "Gorgeous Anarkali dress with embroidered detailing for festive occasions and parties. #AmazonFinds #FashionLootDeals",
    metaDescription: "Gorgeous Anarkali dress with embroidered detailing for festive occasions and parties.",
    seoKeywords: "purple anarkali dress under ₹899, amazon finds, fashion loot deals, womens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #womensfashion",
    affiliateLink: "https://amzn.to/4etamoZ",
    price: 899,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 12483,
    likes: 397,
    saves: 1261,
    amazonClicks: 296,
    pinterestClicks: 1064,
    category: CATEGORIES.find((c) => c.slug === "womens-fashion")!,
    images: [{ id: "19a", url: "https://i.pinimg.com/736x/e9/63/44/e96344b685b0bd8c9e51c48b3daba56c.jpg", alt: "Purple Anarkali Dress Under ₹899", sortOrder: 0 }],
    tags: [{ id: "t19", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "20",
    title: "Stylish Ethnic Kurta Set Under ₹800",
    slug: "stylish-ethnic-kurta-set-under-800",
    seoTitle: "Stylish Ethnic Kurta Set Under ₹800 | Fashion Loot Deals",
    shortDescription: "Beautiful ethnic kurta set for daily wear, festivals, and office looks. Trending Amazon fashion deal.",
    fullDescription: "Beautiful ethnic kurta set for daily wear, festivals, and office looks. Trending Amazon fashion deal. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Stylish Ethnic Kurta Set Under ₹800 ✨",
    pinterestDescription: "Beautiful ethnic kurta set for daily wear, festivals, and office looks. Trending Amazon fashion deal. #AmazonFinds #FashionLootDeals",
    metaDescription: "Beautiful ethnic kurta set for daily wear, festivals, and office looks. Trending Amazon fashion deal.",
    seoKeywords: "stylish ethnic kurta set under ₹800, amazon finds, fashion loot deals, womens fashion",
    hashtags: "#AmazonFinds #FashionLootDeals #womensfashion",
    affiliateLink: "https://amzn.to/4tzWqxf",
    price: 800,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 7292,
    likes: 256,
    saves: 1139,
    amazonClicks: 260,
    pinterestClicks: 1059,
    category: CATEGORIES.find((c) => c.slug === "womens-fashion")!,
    images: [{ id: "20a", url: "https://i.pinimg.com/736x/5a/37/75/5a377563a0d12764e8b89c53e6dba886.jpg", alt: "Stylish Ethnic Kurta Set Under ₹800", sortOrder: 0 }],
    tags: [{ id: "t20", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "21",
    title: "Premium Men's Sneakers Under ₹549",
    slug: "premium-mens-sneakers-under-549",
    seoTitle: "Premium Men's Sneakers Under ₹549 | Fashion Loot Deals",
    shortDescription: "Ultra lightweight sneakers with cushioned comfort and anti-slip sole for gym, travel, and daily wear.",
    fullDescription: "Ultra lightweight sneakers with cushioned comfort and anti-slip sole for gym, travel, and daily wear. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Premium Men's Sneakers Under ₹549 ✨",
    pinterestDescription: "Ultra lightweight sneakers with cushioned comfort and anti-slip sole for gym, travel, and daily wear. #AmazonFinds #FashionLootDeals",
    metaDescription: "Ultra lightweight sneakers with cushioned comfort and anti-slip sole for gym, travel, and daily wear.",
    seoKeywords: "premium men's sneakers under ₹549, amazon finds, fashion loot deals, amazon finds",
    hashtags: "#AmazonFinds #FashionLootDeals #amazonfinds",
    affiliateLink: "https://amzn.to/4dtzZFp",
    price: 549,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: true,
    views: 16209,
    likes: 707,
    saves: 1385,
    amazonClicks: 130,
    pinterestClicks: 246,
    category: CATEGORIES.find((c) => c.slug === "amazon-finds")!,
    images: [{ id: "21a", url: "https://i.pinimg.com/736x/9f/c2/ae/9fc2ae47bb7c9276f15af3fd1b5cf608.jpg", alt: "Premium Men's Sneakers Under ₹549", sortOrder: 0 }],
    tags: [{ id: "t21", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "22",
    title: "Floral Nail Art Stickers | DIY Flower Nail Designs",
    slug: "floral-nail-art-stickers-diy-flower-nail-designs",
    seoTitle: "Floral Nail Art Stickers | DIY Flower Nail Designs | Fashion Loot Deals",
    shortDescription: "50+ cute floral nail sticker designs. Easy peel & apply for gel, acrylic, and natural nails.",
    fullDescription: "50+ cute floral nail sticker designs. Easy peel & apply for gel, acrylic, and natural nails. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Floral Nail Art Stickers | DIY Flower Nail Designs ✨",
    pinterestDescription: "50+ cute floral nail sticker designs. Easy peel & apply for gel, acrylic, and natural nails. #AmazonFinds #FashionLootDeals",
    metaDescription: "50+ cute floral nail sticker designs. Easy peel & apply for gel, acrylic, and natural nails.",
    seoKeywords: "floral nail art stickers | diy flower nail designs, amazon finds, fashion loot deals, beauty",
    hashtags: "#AmazonFinds #FashionLootDeals #beauty",
    affiliateLink: "https://amzn.to/4uBn89K",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 14135,
    likes: 770,
    saves: 933,
    amazonClicks: 126,
    pinterestClicks: 315,
    category: CATEGORIES.find((c) => c.slug === "beauty")!,
    images: [{ id: "22a", url: "https://i.pinimg.com/736x/a6/30/c1/a630c10b50814400d8ac66c40c384266.jpg", alt: "Floral Nail Art Stickers | DIY Flower Nail Designs", sortOrder: 0 }],
    tags: [{ id: "t22", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "23",
    title: "Starry Rhinestone Nail Design | Elegant Glitter Nails",
    slug: "starry-rhinestone-nail-design-elegant-glitter-nails",
    seoTitle: "Starry Rhinestone Nail Design | Elegant Glitter Nails | Fashion Loot Deals",
    shortDescription: "Elegant nude almond nails with sparkling crystal rhinestone accents for parties and weddings.",
    fullDescription: "Elegant nude almond nails with sparkling crystal rhinestone accents for parties and weddings. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Starry Rhinestone Nail Design | Elegant Glitter Nails ✨",
    pinterestDescription: "Elegant nude almond nails with sparkling crystal rhinestone accents for parties and weddings. #AmazonFinds #FashionLootDeals",
    metaDescription: "Elegant nude almond nails with sparkling crystal rhinestone accents for parties and weddings.",
    seoKeywords: "starry rhinestone nail design | elegant glitter nails, amazon finds, fashion loot deals, beauty",
    hashtags: "#AmazonFinds #FashionLootDeals #beauty",
    affiliateLink: "https://amzn.to/4d3ZNI3",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: false,
    views: 5770,
    likes: 731,
    saves: 825,
    amazonClicks: 203,
    pinterestClicks: 967,
    category: CATEGORIES.find((c) => c.slug === "beauty")!,
    images: [{ id: "23a", url: "https://i.pinimg.com/736x/ad/65/4a/ad654a1be4395c3f395632dd74a8efb4.jpg", alt: "Starry Rhinestone Nail Design | Elegant Glitter Nails", sortOrder: 0 }],
    tags: [{ id: "t23", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "24",
    title: "Insulated Travel Mug | Cold 40hrs & Hot 8hrs",
    slug: "insulated-travel-mug-cold-40hrs-hot-8hrs",
    seoTitle: "Insulated Travel Mug | Cold 40hrs & Hot 8hrs | Fashion Loot Deals",
    shortDescription: "Premium stainless steel insulated tumbler. Leak-resistant, BPA-free, fits most car cup holders.",
    fullDescription: "Premium stainless steel insulated tumbler. Leak-resistant, BPA-free, fits most car cup holders. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Insulated Travel Mug | Cold 40hrs & Hot 8hrs ✨",
    pinterestDescription: "Premium stainless steel insulated tumbler. Leak-resistant, BPA-free, fits most car cup holders. #AmazonFinds #FashionLootDeals",
    metaDescription: "Premium stainless steel insulated tumbler. Leak-resistant, BPA-free, fits most car cup holders.",
    seoKeywords: "insulated travel mug | cold 40hrs & hot 8hrs, amazon finds, fashion loot deals, health fitness",
    hashtags: "#AmazonFinds #FashionLootDeals #healthfitness",
    affiliateLink: "https://amzn.to/4uGQ6pj",
    price: undefined,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: false,
    views: 16735,
    likes: 656,
    saves: 592,
    amazonClicks: 174,
    pinterestClicks: 154,
    category: CATEGORIES.find((c) => c.slug === "health-fitness")!,
    images: [{ id: "24a", url: "https://i.pinimg.com/736x/9c/9d/f6/9c9df6eec82244ca32e5879806cf51ed.jpg", alt: "Insulated Travel Mug | Cold 40hrs & Hot 8hrs", sortOrder: 0 }],
    tags: [{ id: "t24", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "25",
    title: "Optimum Nutrition Whey Protein | ₹3779 Deal",
    slug: "optimum-nutrition-whey-protein-3779-deal",
    seoTitle: "Optimum Nutrition Whey Protein | ₹3779 Deal | Fashion Loot Deals",
    shortDescription: "24g protein per serving with 5.5g BCAAs. Supports muscle growth, recovery, and performance.",
    fullDescription: "24g protein per serving with 5.5g BCAAs. Supports muscle growth, recovery, and performance. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Optimum Nutrition Whey Protein | ₹3779 Deal ✨",
    pinterestDescription: "24g protein per serving with 5.5g BCAAs. Supports muscle growth, recovery, and performance. #AmazonFinds #FashionLootDeals",
    metaDescription: "24g protein per serving with 5.5g BCAAs. Supports muscle growth, recovery, and performance.",
    seoKeywords: "optimum nutrition whey protein | ₹3779 deal, amazon finds, fashion loot deals, health fitness",
    hashtags: "#AmazonFinds #FashionLootDeals #healthfitness",
    affiliateLink: "https://amzn.to/4xhSLYj",
    price: 3779,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: false,
    isDeal: true,
    views: 11086,
    likes: 532,
    saves: 257,
    amazonClicks: 171,
    pinterestClicks: 174,
    category: CATEGORIES.find((c) => c.slug === "health-fitness")!,
    images: [{ id: "25a", url: "https://i.pinimg.com/736x/05/54/2a/05542a7d08ae01120c3d0bfe50f98409.jpg", alt: "Optimum Nutrition Whey Protein | ₹3779 Deal", sortOrder: 0 }],
    tags: [{ id: "t25", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
  {
    id: "26",
    title: "Portable USB Blender Under ₹299",
    slug: "portable-usb-blender-under-299",
    seoTitle: "Portable USB Blender Under ₹299 | Fashion Loot Deals",
    shortDescription: "USB rechargeable portable blender for smoothies, shakes, and protein drinks on the go.",
    fullDescription: "USB rechargeable portable blender for smoothies, shakes, and protein drinks on the go. Shop now on Amazon before this deal ends!",
    pinterestTitle: "Portable USB Blender Under ₹299 ✨",
    pinterestDescription: "USB rechargeable portable blender for smoothies, shakes, and protein drinks on the go. #AmazonFinds #FashionLootDeals",
    metaDescription: "USB rechargeable portable blender for smoothies, shakes, and protein drinks on the go.",
    seoKeywords: "portable usb blender under ₹299, amazon finds, fashion loot deals, kitchen gadgets",
    hashtags: "#AmazonFinds #FashionLootDeals #kitchengadgets",
    affiliateLink: "https://amzn.to/4a1T5QH",
    price: 299,
    originalPrice: undefined,
    features: [],
    pros: ["Great value for money", "Trending on Pinterest", "Fast Amazon delivery"],
    cons: ["Limited stock available"],
    status: "PUBLISHED",
    isTrending: true,
    isDeal: true,
    views: 8067,
    likes: 493,
    saves: 1217,
    amazonClicks: 208,
    pinterestClicks: 970,
    category: CATEGORIES.find((c) => c.slug === "kitchen-gadgets")!,
    images: [{ id: "26a", url: "https://i.pinimg.com/736x/bc/3e/4d/bc3e4d64bf7a0edc9f4e2ffd6d42f335.jpg", alt: "Portable USB Blender Under ₹299", sortOrder: 0 }],
    tags: [{ id: "t26", name: "Amazon Finds", slug: "amazon-finds" }],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  }
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "b1",
    title: "Top Amazon Fashion Finds from Fashion Loot Deals",
    slug: "top-amazon-fashion-finds",
    excerpt: "Discover the best men's and women's fashion deals trending on Pinterest from Fashion Loot Deals.",
    content: "## Men's Fashion Deals\n\nFrom casual shirts to co-ord sets, these Amazon finds are going viral on Pinterest.\n\n## Women's Ethnic Wear\n\nStunning lehengas, sarees, and kurta sets at unbeatable prices.\n\n## Health & Kitchen\n\nPortable blenders, protein supplements, and more daily essentials.\n\n## Shop Now\n\nBrowse our curated collection and grab these deals before they're gone!",
    featuredImage: "https://i.pinimg.com/736x/48/ea/71/48ea71427f6ba8913b80102e0b4ee9e2.jpg",
    metaTitle: "Top Amazon Fashion Finds | Fashion Loot Deals",
    metaDescription: "Best Amazon fashion deals for men and women curated from Fashion Loot Deals Pinterest.",
    seoKeywords: "amazon fashion deals, fashion loot deals, pinterest finds",
    status: "PUBLISHED",
    views: 3200,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-07T10:00:00Z",
  },
];
